name: Arduino Library CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  arduino-compile:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        board:
          - fqbn: "arduino:avr:uno"
            platform: "arduino:avr"
            index_url: ""
          - fqbn: "arduino:avr:mega"
            platform: "arduino:avr"
            index_url: ""
          - fqbn: "esp32:esp32:esp32"
            platform: "esp32:esp32"
            index_url: "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"
          - fqbn: "esp8266:esp8266:nodemcuv2"
            platform: "esp8266:esp8266"
            index_url: "https://arduino.esp8266.com/stable/package_esp8266com_index.json"
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1
      
    - name: Update package index
      run: arduino-cli core update-index
      
    - name: Install additional package index
      if: ${{ matrix.board.index_url != '' }}
      run: arduino-cli core update-index --additional-urls "${{ matrix.board.index_url }}"
      
    - name: Install platform with additional URL
      if: ${{ matrix.board.index_url != '' }}
      run: arduino-cli core install ${{ matrix.board.platform }} --additional-urls "${{ matrix.board.index_url }}"
      
    - name: Install platform (standard)
      if: ${{ matrix.board.index_url == '' }}
      run: arduino-cli core install ${{ matrix.board.platform }}
        
    - name: Create symbolic link to library
      run: |
        mkdir -p ~/Arduino/libraries/JuncTek_BatteryMonitor
        ln -s $PWD/JuncTek_BatteryMonitor.h ~/Arduino/libraries/JuncTek_BatteryMonitor/
        ln -s $PWD/JuncTek_BatteryMonitor.cpp ~/Arduino/libraries/JuncTek_BatteryMonitor/
        ln -s $PWD/library.properties ~/Arduino/libraries/JuncTek_BatteryMonitor/
        
    - name: List available examples
      run: |
        echo "Available examples:"
        find examples -name "*.ino" -type f
        
    - name: Compile BasicUsage example
      run: arduino-cli compile --fqbn ${{ matrix.board.fqbn }} examples/BasicUsage
      
    - name: Compile JuncTek_Example (if exists)
      run: |
        if [ -f "examples/JuncTek_Example.ino" ]; then
          # Create a temporary directory for the standalone .ino file
          mkdir -p temp_example/JuncTek_Example
          cp examples/JuncTek_Example.ino temp_example/JuncTek_Example/
          arduino-cli compile --fqbn ${{ matrix.board.fqbn }} temp_example/JuncTek_Example
        else
          echo "JuncTek_Example.ino not found, skipping"
        fi
